repo_name: CRDigitalAndMining/python-uv
repo_url: https://github.com/CRDigitalAndMining/python-uv
site_name: python-uv
site_url: https://CRDigitalAndMining.github.io/python-uv

theme:
  name: material

  icon:
    repo: fontawesome/brands/github

  palette:
    - media: "(prefers-color-scheme: light)"
      primary: blue grey
      scheme: light
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: blue grey
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - content.code.copy
    - navigation.expand
    - navigation.indexes
    - navigation.top

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      linenums: true
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - Getting Started:
      - getting-started/index.md
      - Docker: getting-started/docker.md
      - VS Code: getting-started/vscode.md
      - Dev Container: getting-started/devcontainer.md
  - Guides:
      - guides/index.md
      - uv: guides/uv.md
      - Ruff: guides/ruff.md
      - Pyright: guides/pyright.md
      - pre-commit: guides/pre-commit.md
      - Test: guides/test.md
      - tools:
          - guides/tools/index.md
          - config: guides/tools/config.md
          - logger: guides/tools/logger.md
          - trace: guides/tools/tracer.md
  - Configurations:
      - configurations/index.md
      - uv: configurations/uv.md
      - Ruff: configurations/ruff.md
      - Pyright: configurations/pyright.md
      - pre-commit: configurations/pre-commit.md
      - Test: configurations/test.md
      - Environment Variables: configurations/environment-variables.md
  - Usecases:
      - usecases/index.md
      - JupyterNotebook: usecases/jupyter.md
      - FastAPI: usecases/fastapi.md
      - OpenCV: usecases/opencv.md
  - Deployment:
      - deployment/index.md
      - Azure: deployment/azure.md
      - Docker Production: deployment/docker.md
      - Secrets Management: deployment/secrets.md
      - Monitoring & Logging: deployment/monitoring.md
  - About:
      - License: about/license.md

extra:
  generator: false

copyright: Copyright &copy; 2024-2025 CRDigitalAndMining
